import Head from 'next/head'
import { PageHeader } from '@/components/page-header'
import { Box, Button, ButtonGroup, Flex, Grid, GridItem, Heading, Image, ListItem, Text, UnorderedList } from '@chakra-ui/react'
import Link from 'next/link'
import { GradientHeading } from '@/components/custom-chakra-ui'


export default function Home() {
  return (
    <>
      <Head>
        <title>Bocchi Talk Top</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box id='headerArea' maxH='800px' bg='greenyellow' overflowY='hidden'>
          <PageHeader />
          <Grid
            px='10%'
            py='100px'
            gridTemplateAreas={`
          "heroImage heading"
          "heroImage description"
          "heroImage button"
        `}
            gridTemplateColumns="40% 1fr"
            gridTemplateRows="max-content max-content 1fr"
            columnGap='50px'
          >
            <GridItem area={"heroImage"}>
              <Image maxH='800px' src='/top-page-mobile1.png' alt='hero image' />
            </GridItem>
            <GridItem area={"heading"}>
              <GradientHeading as='h1' size='2xl' wordBreak='keep-all'>ぼっちでもAIと(英)会話しよう！</GradientHeading>
              <Heading mt='20px' color='black' as='h2' size='lg'>Let's Talk anytime, anywhere!</Heading>
            </GridItem>
            <GridItem mt='50px' area={"description"}>
              <Text fontSize='24px' lineHeight='10'>
                <p>Bocchi Talkは学生が開発した、AIと英会話ができるサービスです。</p>
                <p>いつでもどこでも、自分のペースで英会話を学ぶことができます。</p>
                <p>たとえぼっちでも大丈夫！</p>
              </Text>
            </GridItem>
            <GridItem mt='50px' area={"button"}>
              <ButtonGroup spacing='30px'>
                <Link href='/login' passHref>
                  <Button as='a' colorScheme='green' size='lg'>ログインしてみる</Button>
                </Link>
                <Link href='/chat' passHref>
                  <Button as='a' colorScheme='pink' color='white' size='lg'>チャットを始めてみる</Button>
                </Link>
              </ButtonGroup>
            </GridItem>
          </Grid>
        </Box>
        <Box bg='white' px='30px' py='100px'>
          <Heading textAlign='left' as='h2' size='2xl' lineHeight='1.5'>Bocchi Talkの特徴</Heading>

        </Box>
        <Box bg='white' px='30px' py='100px'>
          <Heading textAlign='right' as='h2' size='2xl' lineHeight='1.5'>驚異のほとんど世の中全ての言語に対応！</Heading>
          <Flex mt='100px'>
            <Image w='50vw' src='/top-page-earth.svg' />
            <Text fontSize='24px' lineHeight='10' ml='50px'>
              <p>ぼっちトークは、世界中の言語に対応しています！</p>
              <p>ChatGPTのシステムを利用することで、世の中に存在するほとんど全ての言語で会話をすることが出来ます！</p>
            </Text>
          </Flex>
        </Box>
        <Box>
          <Heading textAlign='center' mt='100px' mb='50px' as='h2' size='2xl' lineHeight='1.5'>こんな人におすすめ</Heading>
          <UnorderedList w='max-content' my='100px' mx='auto' spacing='20px' fontSize='20px'>
            <ListItem>英語を話すのが恥ずかしい。</ListItem>
            <ListItem>英語を話すのが怖い。</ListItem>
            <ListItem>英語を話すのが苦手。</ListItem>
            <ListItem>英語を話すのが緊張する。</ListItem>
            <ListItem>英語を話すのが不安。</ListItem>
          </UnorderedList>
        </Box>
      </main>
    </>
  )
}
