import Head from 'next/head'
import { PageHeader } from '@/components/page-header'
import { Box, Checkbox, Flex, Heading, Image, Text } from '@chakra-ui/react'
import { ButtonLink, GradientHeading, LoginButton, PrimaryButton, Text100, Text110, Title100 } from '@/components/custom-chakra-ui'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import { getServerSession } from 'next-auth'

export default function Home() {
  const reasons = [
    {
      "key": 1,
      "isReverse": false,
      "imagePath": '/multi-lang-chat-mobile.png',
      "title": "驚異の世界中の言語に対応！",
      "text": "Bocchi Talkは、理論上、世の中全ての言語に対応しています！<br />ChatGPTを利用することで、世の中に存在するほとんど全ての言語で会話をすることが出来ます！",
    },
    {
      "key": 2,
      "isReverse": true,
      "imagePath": '/feature-proofread-mobile.png',
      "title": "文章校正で正しく言語を話そう！",
      "text": "Bocchi Talkはデフォルトで文章校正機能を備えています。<br />正しく言語を話せるように、文法チェックと適切なフレーズの提案を行ってくれます！<br />正しい言語を話せていたら、校正についてのメッセージは表示されません！",
    },
    {
      "key": 3,
      "isReverse": false,
      "imagePath": '/feature-option-mobile.png',
      "title": "アシスト機能で効率的に学ぼう！",
      "text": "Bocchi Talkは、オプションメニューにも様々な機能が用意されています。<br />例えば、辞書機能は文章の翻訳から使用される品詞の解説、2つの言語での例文紹介などが使えます！<br />今後アップデートによって追加される可能性もありますので、ぜひフィードバックから機能追加をリクエストしてください！",
    },
  ]
  return (
    <>
      <Head>
        <title>Bocchi Talk Top</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box id='headerSection' h={{ base: 'full', lg: '700px' }} maxW='1080px' px={{ base: '20px', lg: '0' }} mx='auto' overflowY='hidden'>
          <PageHeader />
          <Flex direction={{ base: 'column-reverse', lg: 'row' }} align={{ base: 'center', lg: 'flex-start' }} justify='center' gap='50px'
            maxW='inherit' pt={{ base: '30px', lg: '80px' }} pb={{ base: '50px', lg: '0' }} mx='auto'>
            <Image w={{ base: '300px', md: '350px' }} src='/hero-mobile.png' alt='hero image' />
            <Flex direction='column' rowGap={{ base: '30px', lg: '50px' }}>
              <Flex direction='column' align='flex-start' rowGap={{ base: '30px', lg: '50px' }}>
                <Box>
                  <GradientHeading as='h1' fontSize='40px'>ぼっちでもAIと会話しよう！</GradientHeading>
                  <Heading mt='20px' color='black' as='h2' fontSize='32px' fontWeight='bold'>Talk any-time / where!</Heading>
                </Box>
                <Flex direction='column' align={{ base: 'center', lg: 'flex-start' }} gap='20px'>
                  <Box fontSize={{ base: '16px', lg: '20px' }} lineHeight='150%'>
                    <Text>Bocchi Talkは学生が開発した、AIと英会話ができるサービスです。</Text>
                    <Text>いつでもどこでも、自分のペースで英会話を学ぶことができます。</Text>
                    <Text>たとえぼっちでも大丈夫！</Text>
                  </Box>
                  <Flex direction={{ base: 'column', lg: 'row' }} align='center' gap='20px'>
                    <ButtonLink href='/#target-user'>こんな人におすすめ</ButtonLink>
                    <ButtonLink href='/#features'>機能を見る</ButtonLink>
                  </Flex>
                </Flex>
              </Flex>
              <Flex direction='column' align='center' rowGap='10px'>
                <LoginButton />
                <Checkbox borderColor='black'>利用規約、プライバシーポリシーに同意する</Checkbox>
              </Flex>
            </Flex>
          </Flex>
        </Box>

        <Box w='100%' py='80px' bgGradient='linear(to-br, #1DBEE1, #487EE7, #884FE4)' borderTopLeftRadius='80px'>
          <Flex direction={{ base: 'column', lg: 'row' }} align='center' justify={{ base: 'center', lg: 'space-between' }}
            w={{ base: '100%', lg: '1080px' }} px={{ base: '20px', lg: '0' }} mx='auto'>
            <Flex direction='column' gap={{ base: '50px', lg: '80px' }} w={{ base: 'full', lg: '520px' }}>
              <Title100 color='white'>
                会話が思い通りにいかない？<br />
                人間だもの。<br />
                だからAIとお話ししよう！
              </Title100>
              <Flex direction='column' rowGap='30px'>
                <Text100 color='white'>会話するときに次のようなことにうんざりしていませんか？</Text100>
                <Flex direction='column' rowGap='20px' w='full' px={{ base: '20px', lg: '40px' }} py='20px' bg='rgba(255, 255, 255, 0.5)' borderRadius='40px'>
                  <Flex align='center' columnGap='20px'>
                    <Image src='/beforeList.svg' h='16px' />
                    <Text100>言葉遣いや、相手の機嫌に気を遣う</Text100>
                  </Flex>

                  <Flex align='center' columnGap='20px'>
                    <Image src='/beforeList.svg' h='16px' />
                    <Text100>言葉遣いや、相手の機嫌に気を遣う</Text100>
                  </Flex>

                  <Flex align='center' columnGap='20px'>
                    <Image src='/beforeList.svg' h='16px' />
                    <Text100>言葉遣いや、相手の機嫌に気を遣う</Text100>
                  </Flex>
                </Flex>
                <Text100 color='white'>
                  人とのコミュニケーションは素晴らしいですが、相手が
                  ヒトだからこそ抱える問題があります。<br />
                  これは学習機会において弊害でしかありません。
                </Text100>
              </Flex>
            </Flex>

            <Image display={{ base: 'none', lg: 'block' }} w='300px' borderRadius='36px' src='/lets-chat-mobile.png' alt='hero image' />
          </Flex>
        </Box>

        <Flex align='center' justify='center' gap='30px' h={{ base: 'full', lg: '300px' }} w='100%' px='20px' py={{ base: '50px', lg: '0' }}>
          <Box h='2px' w={{ base: '30px', lg: '50px' }} bg='black' borderRadius='1px'></Box>

          <Title100>
            だから、私は<Box as='br' display={{ base: 'block', lg: 'none' }} />
            Bocchi Talkを<Box as='br' display={{ base: 'block', md: 'none' }} />
            使っています
          </Title100>

          <Box h='2px' w={{ base: '30px', lg: '50px' }} bg='black' borderRadius='1px'></Box>
        </Flex>

        {reasons.map((reason) => (
          <Box w='100%' key={reason.key}>
            <Flex direction={{ base: 'column-reverse', lg: reason.isReverse ? 'row-reverse' : 'row' }} align='center' justify='center' gap='50px'
              w={{ base: '100%', lg: '1080px' }} py={{ base: '50px', lg: '0px' }} px={{ base: '20px', lg: '0' }} mx='auto'>
              <Image w='250px' src={reason.imagePath} alt='hero image' />

              <Flex direction='column' rowGap='50px' w={{ base: 'full', lg: '600px' }}>
                <GradientHeading as='h2' fontSize='32px' wordBreak='keep-all'>{reason.title}</GradientHeading>
                <Text110>{reason.text}</Text110>
              </Flex>
            </Flex>
          </Box>
        ))}

        <Flex direction='column' align='center' rowGap='30px' py='100px' mx='auto'>
          <Text fontSize='20px' lineHeight='150%'>追加機能を募集しています！！</Text>
          <PrimaryButton>機能をリクエストする</PrimaryButton>
        </Flex>

        <Flex id='target-user' direction='column' align='center' w='full' py='100px' bg='#884FE4'>
          <Title100 color='white'>こんな人におすすめ</Title100>

          <Flex direction={{ base: 'column', lg: 'row' }} align='center' gap='50px' py={{ base: '80px', lg: '100px' }}>
            <Flex direction='column' rowGap='30px' w='300px'>
              <Box h='200px' bg='white' borderRadius='20px'></Box>
              <Text100 color='white'>
                英会話を始めてみたいけど、いきなり対面で始めるのは大変そう。
                日本語で質問できないのは致命的なので始められない。
              </Text100>
            </Flex>

            <Flex direction='column' rowGap='30px' w='300px'>
              <Box h='200px' bg='white' borderRadius='20px'></Box>
              <Text100 color='white'>
                英会話をやっているけど、レッスンの時間を制限されるのが嫌。
                講師の方に気を使って思いっきり取り組めない。
              </Text100>
            </Flex>

            <Flex direction='column' rowGap='30px' w='300px'>
              <Box h='200px' bg='white' borderRadius='20px'></Box>
              <Text100 color='white'>
                英会話を長くやっているけど、もう少しディープな話題やマイペースで進めるなど自由に会話を楽しみたい。
              </Text100>
            </Flex>
          </Flex>

          <Flex direction='column' align='center' rowGap='50px' py='100px'>
            <Title100 color='white'>早速始めよう！</Title100>
            <LoginButton />
          </Flex>
        </Flex>

        <Flex direction='column' align='center' py='50px' bg='greenyellow'>
          <Text100>&copy; 2023~ Bocchi Talk App.</Text100>
          <Text100>All rights reserved.</Text100>
        </Flex>
      </main>
    </>
  )
}

export const getServerSideProps = async (context) => {
  const session = await getServerSession(context.req, context.res, authOptions);

  if (session) {
    return {
      redirect: {
        destination: '/dashboard',
        permanent: false,
      },
    };
  }

  return {
    props: {},
  }
};