import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'

export default function Qwertayu() {
    return (
        <>
            <Head>
                <title>Bocchi Talk</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>Hello guys!!</h1>
                <Image
                    className={styles.logo}
                    src="/face.jpg"
                    alt="Next.js Logo"
                    width={180}
                    height={180}
                    priority
                />
                <h2>We are on <strong>Bocchi Talk</strong></h2>
                <p>We'll create new conversation tools with ChatGPT</p>
                <h2>About Us</h2>
                <p>We are college students of <a href="https://www.akashi.ac.jp/">Akachi KOSEN</a>.</p>
                <h2>Members</h2>
                <ul>
                    <li>Hengineer (Tomoda Hiroki)</li>
                    <li>Qwert (Murakami Yui)</li>
                </ul>
                <h2>Contact Us</h2>
                <p>If we want to know about us, give a e-mail to this address.</p>
                <p>abcd1234@gmail.com</p>
            </main>
        </>
    )
}